# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green) " 
error_symbol = "[✗](bold red) " 

[directory]
truncation_length = 5
truncation_symbol = "…/"

# packages
[package]
disabled = true

# ruby
[ruby]
#symbol = " " 
disabled = true

# nodejs
[nodejs]
disabled = true

# lua
[lua]
disabled = true

# python
[python]
disabled = true

# rust
[rust]
disabled = true

# java
[java]
disabled = true

# golang
[golang]
disabled = true

# aws
[aws]
disabled = true

# pearl
[perl]
disabled = true
